{
 "title": "Consensus Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_id",
    "query": {
     "query": "label_values(logs_PROPOSING,node_id)"
    }
   },
   {
    "name": "logfile",
    "label": "logfile (schain)",
    "query": {
     "query": "label_values({node_id=\"$node_id\"}, logfile)"
    }
   },
   {
    "name": "proposerIndex",
    "query": {
     "query": "label_values(logs_addBlockProposal{logfile=\"$logfile\", node_id=\"$node_id\"}, proposerIndex)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Block number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logs_BLOCK_COMMIT_max_proposer{node_id=\"$node_id\", logfile=~\"$logfile\"}",
     "legendFormat": "block id"
    }
   ]
  },
  {
   "title": "Block proposals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logs_addBlockProposal{node_id=\"$node_id\", logfile=~\"$logfile\", proposerIndex=~\"$proposerIndex\"}",
     "legendFormat": "proposer={{proposerIndex}}"
    }
   ]
  },
  {
   "title": "Block proposals range",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logs_addBlockProposal{node_id=\"$node_id\", logfile=~\"$logfile\", proposerIndex=~\"$proposerIndex\"}",
     "legendFormat": "proposer={{proposerIndex}}"
    }
   ]
  },
  {
   "title": "DA Proofs total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logs_daProof{node_id=\"$node_id\", logfile=~\"$logfile\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Bin-cons proposing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logs_PROPOSING{node_id=\"$node_id\", logfile=~\"$logfile\"}",
     "legendFormat": "proposed block id"
    }
   ]
  },
  {
   "title": "Bin-cons decided",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logs_decided{node_id=\"$node_id\", logfile=~\"$logfile\"}",
     "legendFormat": "proposer={{proposer}}"
    }
   ]
  }
 ]
}