{
 "title": "Process Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "process",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total,groupname)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_thread_cpu_seconds_total{groupname=\"$process\", instance=\"$instance\", mode=\"user\"}[$__interval])",
     "legendFormat": "{{threadname}}"
    }
   ]
  },
  {
   "title": "Thread CPU Time",
   "type": "graph",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_thread_cpu_seconds_total{groupname=\"$process\", mode=\"user\", instance=\"$instance\"}",
     "legendFormat": "{{threadname}}"
    }
   ]
  },
  {
   "title": "Number of Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_threads{groupname=\"$process\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "FD Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_open_filedesc{groupname=\"$process\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Wchans",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_threads_wchan{groupname=\"$process\", instance=\"$instance\"}",
     "legendFormat": "{{wchan}}"
    }
   ]
  }
 ]
}