{
 "title": "Schains Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node_id",
    "query": {
     "query": "label_values(logs_BLOCK_COMMIT,node_id)"
    }
   },
   {
    "name": "logfile",
    "label": "logfile (schain)",
    "query": {
     "query": "label_values(logs_BLOCK_COMMIT,logfile)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Block number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "repeat": "logfile",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "logs_BLOCK_COMMIT_best_node{logfile=\"$logfile\"}"
    }
   ]
  },
  {
   "title": "Active nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "repeat": "logfile",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(logs_BLOCK_COMMIT_max_proposer{logfile=\"$logfile\"})",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Block rate in $logfile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 0 },
   "repeat": "logfile",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logs_BLOCK_COMMIT_max_proposer{logfile=\"$logfile\", node_id=~\"$node_id\"}[$__interval])",
     "legendFormat": "{{node_id}}"
    },
    {
     "expr": "rate(logs_BLOCK_COMMIT_best_node{logfile=\"$logfile\"}[$__interval])",
     "legendFormat": "best"
    },
    {
     "expr": "rate(logs_BLOCK_COMMIT_best_node{logfile=\"$logfile\"}[$__interval])",
     "legendFormat": "averaged"
    }
   ]
  },
  {
   "title": "Block Number Divergence in $logfile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 0 },
   "repeat": "logfile",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(logs_BLOCK_COMMIT_max_proposer{logfile=\"$logfile\", node_id=~\"$node_id\"})-min(logs_BLOCK_COMMIT_max_proposer{logfile=\"$logfile\", node_id=~\"$node_id\"})",
     "legendFormat": "Block Number Divergence in $logfile"
    }
   ]
  },
  {
   "title": "Proposer stats for $logfile",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "repeat": "logfile",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changes(logs_BLOCK_COMMIT_max_node{logfile=\"$logfile\"}[$__range])",
     "legendFormat": "{{proposer}}"
    }
   ]
  }
 ]
}