{
 "title": "Schain details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "logfile",
    "query": {
     "query": "label_values(logs_BLOCK_COMMIT, logfile)"
    }
   },
   {
    "name": "node_id",
    "query": {
     "query": "label_values(logs_BLOCK_COMMIT, node_id)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(logs_received, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Block number",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logs_BLOCK_COMMIT_max_proposer{logfile=\"$logfile\", node_id=~\"$node_id\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "By node",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "logs_BLOCK_COMMIT_max_proposer{logfile=\"$logfile\", node_id=~\"$node_id\"}",
     "legendFormat": "node_id={{node_id}}"
    }
   ]
  },
  {
   "title": "Txns in block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logs_imported{logfile=\"$logfile\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Txns in received buffer",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logs_received{logfile=\"$logfile\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}